### ISSUE TITLE
questions about fastMNN and mnnCorrect functions

### ISSUE THREAD

**Issue by ahmedabbas81** [LTLA/batchelor#11]
Dear all,
I am asking about the functions fastMNN and mnnCorrect,
I give the functions like mnnCorrect or fastMNN the two gene expression matrices (genes in rows and cells in columns) but I always get
the same error : Error in checkBatchConsistency(batches) :
    row names are not the same across batches
although I kept only the common genes in the two matrices.

Also, from the output variable, how to know which cells from both matrices match with each other?

Thanks
Ahmed

**Comment by LTLA** [comment]
> row names are not the same across batches

They have to be in the same order, too. 

It would help if you provided a minimum working example, see [here](https://reprex.tidyverse.org/articles/articles/learn-reprex.html).

> Also, from the output variable, how to know which cells from both matrices match with each other?

There is a `merge.info$pairs` field in the metadata describing the pairing between cells at each merge step. Specifically, this identifies cells that are identified as MNN pairs - you should keep in mind that this is not the same as actually clustering the cells together.

**Comment by LTLA** [comment]
Assuming that this was resolved.

**Comment by Ramirkhah** [comment]
Hello, I am applying fastMNN to do batch correction in the bulk RNAseq data. I am getting the same error: 

> Error in checkBatchConsistency(batches, cells.in.columns = TRUE) : 
>   number of rows is not the same across batches (see batch "batch")

```
batch_info <- data.frame(batch = meta_combined_with_new_sample$batch)
rownames(batch_info) <- colnames(combined_with_new_sample.1)

## apply fastMNN
mnn <- fastMNN(as.matrix(combined_with_new_sample.1), batch_info, k=20) 
```

This is part of my expression profile:
```
> combined_with_new_sample.1[1:4,1:4]
       RJR18190912_S16_TL16    RJR18190912_S17_TL17    RJR18190912_S18_TL18    RJR18190912_S19_TL19
PPHLN1             6.042217             5.849062             5.948529             6.222981
FEM1A              3.958475             4.538115             4.643450             3.689538
A1CF               1.969016             4.272028             3.934763             4.066292
A2M                6.604406            10.644650             6.691179             6.222981
```

this is part of my batch info:
```
> batch_info
                             batch
RJR18190912_S16_TL16        Batch2
RJR18190912_S17_TL17        Batch2
RJR18190912_S18_TL18        Batch2
RJR18190912_S19_TL19        Batch2
RJR18190912_S20_TL20        Batch2
RJR18190912_S21_TL21        Batch2
RJR18190912_S04_RJ4         Batch2
RJR18190912_S05_RJ5         Batch2
RJR18190912_S06_RJ6         Batch2
RJR18190912_S07_RJ7         Batch2
```
Really appreciate your help!

Thanks,
Raheleh

**Comment by LTLA** [comment]
This issue is closed; open a new issue.
