### ISSUE TITLE
mnnCorrect.R

### ISSUE THREAD

**Issue by getanid123** [LTLA/batchelor#14]
Hi I am new to data analysis and I am trying to do batch correction for three batches of single cell data [counts data obtained from alignment ] as part of my project and I tried using mnnCorrect as follows:

##Execute the below in R  version 3.6.2
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("batchelor")

##I have counts from alignment of three batches 
batch1<-read.csv("file1.csv", skip=1,row.names = 1,header=FALSE, sep='\t')
batch2<-read.csv("file2.csv", skip=1,row.names = 1, header=FALSE,sep='\t')
batch3<-read.csv("file3.csv", skip=1,row.names = 1, header=FALSE,sep='\t')

##and I modified the code below at only two places:
##1. mnnCorrect <- function(batch1,batch2,batch3, batch=NULL, restrict=3, k=20,..
##2. original <- batches <- .unpack_batches(batch1,batch2,batch3)

##----code modified as mentioned above and excited in R-----
mnnCorrect <- function(batch1,batch2,batch3, batch=NULL, restrict=3, k=20, prop.k=NULL, sigma=0.1, 
                       cos.norm.in=TRUE, cos.norm.out=TRUE, svd.dim=0L, var.adj=TRUE, 
                       subset.row=NULL, correct.all=FALSE, merge.order=NULL, auto.merge=FALSE, 
                       assay.type="logcounts", BSPARAM=ExactParam(), BNPARAM=KmknnParam(), BPPARAM=SerialParam())
{
  original <- batches <- .unpack_batches(batch1,batch2,batch3)
  checkBatchConsistency(batches)
  restrict <- checkRestrictions(batches, restrict)
  
  # Pulling out information from the SCE objects.        
  is.sce <- checkIfSCE(batches)
  if (any(is.sce)) {
    batches[is.sce] <- lapply(batches[is.sce], assay, i=assay.type, withDimnames=FALSE)
  }
  
  # Subsetting by 'batch'.
  do.split <- length(batches)==1L
  if (do.split) {
    divided <- divideIntoBatches(batches[[1]], batch=batch, restrict=restrict[[1]])
    batches <- divided$batches
    restrict <- divided$restrict
  }
  
  # Setting up the parallelization environment.
  if (.bpNotSharedOrUp(BPPARAM)) {
    bpstart(BPPARAM)
    on.exit(bpstop(BPPARAM), add=TRUE)
  }
  
  output <- do.call(.mnn_correct, c(batches, 
                                    list(k=k, prop.k=prop.k, sigma=sigma, cos.norm.in=cos.norm.in, cos.norm.out=cos.norm.out, svd.dim=svd.dim, 
                                         var.adj=var.adj, subset.row=subset.row, correct.all=correct.all, restrict=restrict,
                                         merge.order=merge.order, auto.merge=auto.merge, 
                                         BSPARAM=BSPARAM, BNPARAM=BNPARAM, BPPARAM=BPPARAM)))
  
  # Reordering the output for correctness.
  if (do.split) {
    d.reo <- divided$reorder
    output <- output[,d.reo,drop=FALSE]
    metadata(output)$merge.info$pairs <- .reindex_pairings(metadata(output)$merge.info$pairs, d.reo)
  }
  .rename_output(output, original, subset.row=subset.row)
}

-------------------------end of execution

There was no output from the above code [though everything is executed and no error was thrown.
I tried to access 'output' object but I got [ Error: object 'output' not found]

Can you please help me understand where I am going wrong? or if my execution is wrong?

Please guide me to how I can obtain the batch corrected count reads. Thanks a lot for your help in advance.

**Comment by LTLA** [comment]
I can't say I have much sympathy for you in this case. If you have problems with the original `mnnCorrect()` in the released version of **batchelor**, I am willing to help you there, but if you're modifying the package code you had better know what you're doing.

**Comment by getanid123** [comment]
Hi LTLA,
Sorry for wording it differently. When I say I modified the code, I meant I added the batches information as per the suggestions in comments before the code. So, I  showed where exactly I have added the batches information in the mnnCorrect() function. But I am not able to generate any output. 

Can you please help with where I am going wrong. I think I did exactly as asked for.

Thanks for your help in advance!!

**Comment by LTLA** [comment]
I still don't understand why you felt the need to show me the internals of `mnnCorrect`.

Just tell me what **batchelor** commands you ran. A minimal reproducible example would be ideal, see [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) for what that means. If you cannot share the data, just make some up to reproduce the bug.

**Comment by getanid123** [comment]
Hi LTLA, 
Let me confirm that your code is running perfectly without any error. But I can't see any output displayed.

if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("batchelor")
batch1 <- read.csv("/path/batch1.csv", skip=1,row.names = 1,header=FALSE)
batch2<-read.csv("/path/batch2.csv", skip=1,row.names = 1,header=FALSE)
batch3<-read.csv("/path/batch3.csv", skip=1,row.names = 1,header=FALSE)
mnnCorrect <- function(batch1,batch2,batch3, batch=NULL, ... //rest of code//

I tried to write output [as I think it holds the final results]
>write.csv(output,"/Users/xxx/xxx/mnn1.csv" )
Got below error
Error in is.data.frame(x) : object 'output' not found
 I tried to write mnnCorrect to see what it is holding
>write.csv(mnnCorrect,"/Users/xxx/xxx/mnn2.csv" )
Got below error
Error in as.data.frame.default(x[[i]], optional = TRUE) : cannot coerce class ‘"function"’ to a data.frame
Hope I am making sense as this is new to me. Please suggest how I can access the results.

**Comment by LTLA** [comment]
> ```r
> mnnCorrect <- function(batch1,batch2,batch3, batch=NULL, ... //rest of code//
> ```

I hope that you understand that this simply _(re)defines_ the `mnnCorrect` function. It does not call the function, which is what you need to do in order to get the function's output!

I could go on but the mistake should be fairly obvious by now. If you still don't get it, it would be a good idea to read some introductory materials on programming in R.
