### ISSUE TITLE
Questions regarding multiBatchNorm and fastMNN based correction

### ISSUE THREAD

**Issue by piyushjo15** [LTLA/batchelor#16]
_I previously posted this on bio-conductor support, but later realized here would be better. Also as this is another question, so I made a separate post._

I am trying to use fastMNN approach to integrate multiple datasets. I went through the vignettes for scran and batchelor and tutorial on OSCA to understand how to pre-process my data and then perform fastMNN based correction. Also I followed the advice on this post  https://github.com/LTLA/batchelor/issues/12

But I just wanted to be sure if I am getting this right: I should normalize using clustering based size factors individually (using scran), which would then be adjusted across batches by multiBatchNorm. So it will use the pre-computed normalized data to make adjustment? Also for marker analysis using findmarker and convert to edgeR, will it be using the adjusted normalized values or the raw counts? The reason is as Vieth et al suggested scran normalization with clustering is best way to get best DE estimates, I want to use the clustering based normalized data for the merged data to peform DE analysis.

Also after performing fastMNN, could I check how many of the corrected PCs are explaining the variance just like the elbow plot of normal PCA?

Thanks! Piyush

**Comment by LTLA** [comment]
> _I previously posted this on bio-conductor support, but later realized here would be better. Also as this is another question, so I made a separate post._

Both are fine. That said, I tend to prefer the support site for more "how to use" queries, as I would like to reserve the use of GitHub for feature requests and bug reports.

> I should normalize using clustering based size factors individually (using scran), which would then be adjusted across batches by multiBatchNorm. So it will use the pre-computed normalized data to make adjustment?

Yes, basically. `multiBatchNorm` will only scale on a per-batch basis, not on a per-cell basis. So if you tell it how to scale cells _within_ each batch by providing pre-computed size factors, the function will honor that; it will only scale entire batches up and down to equalize coverage across batches, while preserving the same scaling that was used within the batch.

> Also for marker analysis using findmarker and convert to edgeR, will it be using the adjusted normalized values or the raw counts?

For `findMarkers`, I typically do my DE analyses on the normalized expression values before running `multiBatchNorm`. It probably doesn't make a big practical difference whether you run it before or after; I guess I do it before for the philosophical reason that I like my multi-batch DE comparisons to be computed off the same values that were used for the single-batch comparisons.

For **edgeR**, you must use the raw counts, no exceptions.

> Also after performing fastMNN, could I check how many of the corrected PCs are explaining the variance just like the elbow plot of normal PCA?

This information can be reported by `multiBatchPCA()` but not carried through by `fastMNN()`. I guess I could report it but it is not particularly useful. Recall that, in the case of a multi-batch experiment, the PCs also include the batch effects so the elbow plot will probably have its first few PCs dominated by batch-related components. This shifts the elbow point to the left, making it more likely to discard PCs related to genuine biology if you set the number of PCs to the elbow point.

MNN detection also relies on having enough PCs to "capture" the batch vector. Okay, that's pretty vague, but basically it means that if you start throwing away too many PCs, it becomes impossible to distinguish between the batch effect and the biologically-varying dimensions. Hence we have always erred on the side of including more dimensions (50 by default) than are probably necessary.

**Comment by piyushjo15** [comment]
Thanks! This was helpful.

**Comment by LTLA** [comment]
Despite the fact that I don't think it's very useful, I have modified `fastMNN` to optionally return the variance explained in the `metadata` of its output - this should be available in version 1.3.15.
