### ISSUE TITLE
pre-processing for MNN

### ISSUE THREAD

**Issue by shokohirosue** [LTLA/batchelor#24]
Hi Aaron,

I would like to use MNN for batch correction and have a few questions regarding the data pre-processing for MNN. 
At the moment my steps are 1. Filter out empty droplets/low quality cells (for each sample), 2. merge samples in the same batch, 3. normalization within a batch, 4. get HVG, normalize across batches and run MNN.
(My experimental design in detail is described here (https://github.com/LTLA/batchelor/issues/21).)

1. In step 2, which would you recommend, normalising within a batch and normalising within a sample?

2. At which point should I filter out lowly expressed genes (calculateAverage(sce) > 0.1)? I am setting min.mean=0.1 for computeSumFactors and using top 5000 highly variable genes for multiBatchNorm/MNN. Do I still have to worry about filtering out genes before within-batch normalization or batch correction?

Thank you very much for your help.

**Comment by LTLA** [comment]
> In step 2, which would you recommend, normalising within a batch and normalising within a sample?

Usually the idea is to compute size factors within each batch using your method of choice, and then normalizing across batches using `multiBatchNorm()`. The size factors remove differences within batches and `multiBatchNorm()` removes differences between batches. In fact, if you're happy with library size normalization, `multiBatchNorm()` will compute the size factors automatically for you, so you don't even have to do that yourself.

> At which point should I filter out lowly expressed genes (calculateAverage(sce) > 0.1)? I am setting min.mean=0.1 for computeSumFactors and using top 5000 highly variable genes for multiBatchNorm/MNN. Do I still have to worry about filtering out genes before within-batch normalization or batch correction?

You don't have to explicitly filter out lowly expressed genes anymore. Each of the functions will do the filtering internally; for example, `computeSumFactors` will automatically filter out the genes that it doesn't like (see the `min.mean=` argument). As will the various HVG computing functions, e.g., `fitTrendVar` has its own `min.mean=` argument, which is automatically used by `modelGeneVar`. In particular `computeSumFactors`  try to auto-detect if we're dealing with UMI or read count data, and will automatically default to `min.mean=0.1` if dealing with the former.

**Comment by shokohirosue** [comment]
Thank you very much for your reply!
