### ISSUE TITLE
Feature request: fastMNN on PCs

### ISSUE THREAD

**Issue by dagarfield** [LTLA/batchelor#27]
Hi,

Hopefully this is the right place for this.....
....I'm a big fan of fastMNN, but would like to be able to apply it directly to a set of reduced dimensions (PCs, LSI, etc) rather than a single-cell experiment object. I think this was an option in an earlier version of scran, but seems to have vanished more recently.

**Comment by LTLA** [comment]
Perhaps the `reducedMNN()` function might do what you want.

**Comment by dagarfield** [comment]
Apparently I am unable to search packages properly....thanks for the tip!
