### ISSUE TITLE
Error in RunFastMNN with Seurat wrapper

### ISSUE THREAD

**Issue by parkjooyoung99** [LTLA/batchelor#39]
Hello,
I am using RunFastMNN which can be used directly with 'Seurat object'. 
There were no problem with it but all of the sudden, I met this error below. 
Would there be any suggestion to solve this??
Thank you!

` im <- RunFastMNN(object.list = SplitObject(a, split.by = "batch"))`
`Computing 2000 integration features`
`Error in SummarizedExperiment::SummarizedExperiment(assays = assays) : `
  `the rownames and colnames of the supplied assay(s) must be NULL or`
`  identical to those of the SummarizedExperiment object (or derivative)`
 ` to construct`

**Comment by LTLA** [comment]
I didn't implement the wrapper, but my guess would be that the various `assays` have different dimnames, causing the constructor to fail because it can't figure out which ones are "right". See Bioconductor/SummarizedExperiment#57 for some background.

**Comment by parkjooyoung99** [comment]
Thank you!

**Comment by chun-123** [comment]
Have you solved this problem? I meet the same error.
