### ISSUE TITLE
dimnames() differ

### ISSUE THREAD

**Issue by cstrlln** [LTLA/batchelor#4]
Hello,
I'm trying to use multiBatchNorm with two assays (B10 and B01).
I've checked multiple times for naming and number of rows to be equal but still get this error:

> universe <- intersect(rownames(B10), rownames(B01))
> rescaled <- multiBatchNorm(B10[universe,], B01[universe,])
Error in `assays<-`(`*tmp*`, ..., value = `*vtmp*`) : 
  current and replacement dimnames() differ

please advice

**Comment by LTLA** [comment]
That's interesting. Can you do a `traceback()` on the error?

**Comment by cstrlln** [comment]
thanks for response and sorry for delay, out of town at the moment.
This is what I got for the traceback:

> traceback(max.lines=50)
10: stop("current and replacement dimnames() differ")
9: `assays<-`(`*tmp*`, ..., value = `*vtmp*`)
8: `assays<-`(`*tmp*`, ..., value = `*vtmp*`)
7: `assay<-`(`*tmp*`, "logcounts", value = new("DelayedMatrix", 
       seed = new("DelayedUnaryIsoOpStack", OPS = list(function (a) 
       match.fun(.Generic)(a, e2), function (a) 
       match.fun(.Generic)(a)), seed = new("DelayedAperm", perm = 2:1, 
           seed = new("DelayedUnaryIsoOpWithArgs", OP = .Primitive("/"), 
               Largs = list(), Rargs = list(c(1.45546558902197, 
               0.302207715615869, 0.913735564666423, 0.454879317407359, 
               0.120967778737502, 0.880432050780423, 0.957499664406721, 
               0.881792528095296, 0.187551082962615, 1.27174620966927, 
               0.294781674165032, 0.2171376568863, 0.935799194351885, 
               1.29595106002895, 0.397579174313955, 0.388915006009992, 
               1.68148691082767, 1.6182418235014, 0.854441968642696, 
               0.32298337612088, 0.725714069045197, 0.561825489696659, 
               2.70924917854763, 0.52588965015493, 2.77799422457411, 
               2.47267659988966, 0.202845604135013, 3.25018871258028, 
               1.72958407921125, 1.39346618051494, 1.37272271735705, 
               1.32124224300598, 1.58538446394744, 0.287625720438843, 
               0.328006145976937, 0.585833308856448, 0.0975999492103254, 
               2.0496902204285, 0.168619750679371, 1.92799634803797, 
               3.92416419145458, 0.915513872098943, 0.692273143034035, 
               0.781080239062773, 0.56160679137934, 1.00176050125361, 
               0.610172136671191, 0.861200760886092, 1.09774359578755, 
               0.35804056129351, 0.615455569569809, 0.667801766020306, 
               1.68099801988849, 0.69794685411739, 2.44273884975405, 
               2.40623576406644, 1.35601225918444, 1.30780955755733, 
               0.485263867136143, 1.10129033542791, 0.302180965396383, 
               0.367664777867618, 1.59118829510535, 0.283577721762119, 
               1.52046625534248, 0.383088271593, 1.81826348933531, 
               3.64955346500634, 0.172271905367674, 0.79145842109845, 
               1.48851786389423, 1.32435537300384, 2.58890954347712, 
               0.358744052122065, 1.61078115538811, 0.282540350489079, 
               0.988082654267708, 1.29378109840074, 0.974109773036617, 
               2.07526323354764, 0.467747954905986, 0.835146356894409, 
               0.564458693352021, 0.246033829003521, 1.91588357674023, 
               0.973255568104572, 0.436121542112177, 0.705011650073473, 
               1.05301119190182, 0.58893468290822, 0.382523173697831, 
               0.485490117447928, 0.21311311464325, 1.8374747391545, 
               0.201344902500451, 0.961761892077045, 1.00450301159092, 
               1.51441682205273, 0.324773337441145, 0.591310910675045, 
               0.551020864938208, 1.00734516240353, 0.367899867083004, 
               0.891724382762688, 0.526130107829867, 0.181830960999675, 
               0.696614674806908, 3.65730907949143, 0.580890134486349, 
               0.0891904898126757, 0.303626201223046, 4.4694088447956, 
               2.89087239156926, 0.549984275046002, 0.147840356431298, 
               1.91969721311177, 0.410162957567473, 0.135640998002593, 
               0.203089769140291, 0.274267265054577, 1.90110669405581, 
               1.36694087784507, 2.47208759164408, 0.72441691029601, 
               0.162537606658302, 0.986176084307665, 2.29881026160165, 
               0.559389867579887, 0.21571973870459, 1.9732785191947, 
               1.31790097700996, 1.48248779164079, 1.9900035193125, 
    ...
6: `assay<-`(`*tmp*`, "logcounts", value = new("DelayedMatrix", 
       seed = new("DelayedUnaryIsoOpStack", OPS = list(function (a) 
       match.fun(.Generic)(a, e2), function (a) 
       match.fun(.Generic)(a)), seed = new("DelayedAperm", perm = 2:1, 
           seed = new("DelayedUnaryIsoOpWithArgs", OP = .Primitive("/"), 
               Largs = list(), Rargs = list(c(1.45546558902197, 
               0.302207715615869, 0.913735564666423, 0.454879317407359, 
               0.120967778737502, 0.880432050780423, 0.957499664406721, 
               0.881792528095296, 0.187551082962615, 1.27174620966927, 
               0.294781674165032, 0.2171376568863, 0.935799194351885, 
               1.29595106002895, 0.397579174313955, 0.388915006009992, 
               1.68148691082767, 1.6182418235014, 0.854441968642696, 
               0.32298337612088, 0.725714069045197, 0.561825489696659, 
               2.70924917854763, 0.52588965015493, 2.77799422457411, 
               2.47267659988966, 0.202845604135013, 3.25018871258028, 
               1.72958407921125, 1.39346618051494, 1.37272271735705, 
               1.32124224300598, 1.58538446394744, 0.287625720438843, 
               0.328006145976937, 0.585833308856448, 0.0975999492103254, 
               2.0496902204285, 0.168619750679371, 1.92799634803797, 
               3.92416419145458, 0.915513872098943, 0.692273143034035, 
               0.781080239062773, 0.56160679137934, 1.00176050125361, 
               0.610172136671191, 0.861200760886092, 1.09774359578755, 
               0.35804056129351, 0.615455569569809, 0.667801766020306, 
               1.68099801988849, 0.69794685411739, 2.44273884975405, 
               2.40623576406644, 1.35601225918444, 1.30780955755733, 
               0.485263867136143, 1.10129033542791, 0.302180965396383, 
               0.367664777867618, 1.59118829510535, 0.283577721762119, 
               1.52046625534248, 0.383088271593, 1.81826348933531, 
               3.64955346500634, 0.172271905367674, 0.79145842109845, 
               1.48851786389423, 1.32435537300384, 2.58890954347712, 
               0.358744052122065, 1.61078115538811, 0.282540350489079, 
               0.988082654267708, 1.29378109840074, 0.974109773036617, 
               2.07526323354764, 0.467747954905986, 0.835146356894409, 
               0.564458693352021, 0.246033829003521, 1.91588357674023, 
               0.973255568104572, 0.436121542112177, 0.705011650073473, 
               1.05301119190182, 0.58893468290822, 0.382523173697831, 
               0.485490117447928, 0.21311311464325, 1.8374747391545, 
               0.201344902500451, 0.961761892077045, 1.00450301159092, 
               1.51441682205273, 0.324773337441145, 0.591310910675045, 
               0.551020864938208, 1.00734516240353, 0.367899867083004, 
               0.891724382762688, 0.526130107829867, 0.181830960999675, 
               0.696614674806908, 3.65730907949143, 0.580890134486349, 
               0.0891904898126757, 0.303626201223046, 4.4694088447956, 
               2.89087239156926, 0.549984275046002, 0.147840356431298, 
               1.91969721311177, 0.410162957567473, 0.135640998002593, 
               0.203089769140291, 0.274267265054577, 1.90110669405581, 
               1.36694087784507, 2.47208759164408, 0.72441691029601, 
               0.162537606658302, 0.986176084307665, 2.29881026160165, 
               0.559389867579887, 0.21571973870459, 1.9732785191947, 
               1.31790097700996, 1.48248779164079, 1.9900035193125, 
    ...
5: .local(object, ...)
4: (new("standardGeneric", .Data = function (object, ...) 
   standardGeneric("normalize"), generic = "normalize", package = "BiocGenerics", 
       group = list(), valueClass = character(0), signature = "object", 
       default = NULL, skeleton = (function (object, ...) 
       stop("invalid call in method dispatch to 'normalize' (no default method)", 
           domain = NA))(object, ...)))(dots[[1L]][[1L]], exprs_values = "counts", 
       centre_size_factors = FALSE)
3: (new("standardGeneric", .Data = function (object, ...) 
   standardGeneric("normalize"), generic = "normalize", package = "BiocGenerics", 
       group = list(), valueClass = character(0), signature = "object", 
       default = NULL, skeleton = (function (object, ...) 
       stop("invalid call in method dispatch to 'normalize' (no default method)", 
           domain = NA))(object, ...)))(dots[[1L]][[1L]], exprs_values = "counts", 
       centre_size_factors = FALSE)
2: mapply(FUN = normalize, batches, MoreArgs = c(list(exprs_values = assay.type, 
       centre_size_factors = FALSE), norm.args), SIMPLIFY = FALSE)
1: multiBatchNorm(B10[universe, ], B01[universe, ])


####
as side info I had separately done the QC of B10 and B01 in different sessions, stored them as RDS and then loaded them together for batch norm and try to aggregate them.

**Comment by LTLA** [comment]
That problem should be fixed in Bioconductor/SummarizedExperiment#25, update SummarizedExperiment to use the latest BioC-devel version.

**Comment by cstrlln** [comment]
thanks! that worked, don't get the error anymore
