### ISSUE TITLE
Find maker genes using fastMNN output matrix

### ISSUE THREAD

**Issue by zezhuo** [LTLA/batchelor#8]
Hi batchelor team,

I have applied your aggregation mothod fastMNN on my six batches of 10x data. MNN is the best mothod for my data set, comparing with CCA and scMerge. It worked quite well in terms of downstream clustering! But I get some difficulties on finding marker genes of clusters, since most of the methons prefer to use the counts/logNormalized counts matrix. Do you have any mothod recommended for finding marker genes based on your output matrix, which is scaled and centred to zero? 

Regards,
Nelosn

**Comment by LTLA** [comment]
I actually prefer to do the marker detection on the raw expression values, for reasons discussed here:

https://github.com/MarioniLab/FurtherMNN2018/issues/5#issuecomment-528181450
https://osca.bioconductor.org/integrating-datasets.html#using-the-corrected-values

I only use the `fastMNN()` output for cell-based analyses like clustering or trajectory reconstruction. I always go back to the original values for the DE comparisons, after blocking on the batch effect:

https://osca.bioconductor.org/marker-gene-detection.html#marker-batch

Technically, you _could_ do a DE analysis on the corrected values. But: if an interesting gene is DE between clusters in the corrected values but not DE in the originals, I wouldn't trust it.

**Comment by zezhuo** [comment]
Hi @LTLA ,

Thanks for your explanations and suggestions. It is very helpful for me a beginner.

Regards，
Nelson
